CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

BACKBONE: 'resnet'
MODEL: 'voxelpose'
DATA_DIR: ''
GPUS: '2'
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 100

DATASET:
  COLOR_RGB: true
  ROOT: "data/Wusi"
  TRAIN_DATASET: 'synthetic'
  TRAIN_HEATMAP_SRC: 'gt'
  TEST_DATASET: 'wusi'
  TEST_HEATMAP_SRC: 'image'
  ROOTIDX: 2
  CAMERA_NUM: 11
  CAMERA_ID: 
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
  CAMERA_IP:
    - 162.105.158.7
    - 162.105.158.8
    - 162.105.158.9
    - 162.105.158.10
    - 162.105.158.11
    - 162.105.158.12
    - 162.105.158.13
    - 162.105.158.14
    - 162.105.158.15
    - 162.105.158.17
    - 162.105.158.18
  ORI_IMAGE_WIDTH: 2560
  ORI_IMAGE_HEIGHT: 1440

SYNTHETIC:
  CAMERA_FILE: 'calibration_wusi.json'
  POSE_FILE: '../basketball_pose.pkl'
  MAX_PEOPLE: 10
  NUM_DATA: 20000
  DATA_AUGMENTATION: true
  
NETWORK:
  PRETRAINED_BACKBONE: "models/pose_resnet50_panoptic.pth.tar"
  IMAGE_SIZE:
  - 960
  - 512
  HEATMAP_SIZE:
  - 240
  - 128
  NUM_JOINTS: 15
  SIGMA: 3

TRAIN:
  BATCH_SIZE: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 30
  RESUME: true
  OPTIMIZER: adam
  LR: 0.0001

TEST:
  MODEL_FILE: 'model_best.pth.tar'
  BATCH_SIZE: 1

CAPTURE_SPEC:
  SPACE_SIZE:
    - 16000.0
    - 16000.0
    - 3000.0
  SPACE_CENTER:
    - 0.0 
    - -500.0
    - 1500.0
  VOXELS_PER_AXIS:
    - 80
    - 80
    - 20
  MAX_PEOPLE: 10
  MIN_SCORE: 0.2
  
INDIVIDUAL_SPEC:
  SPACE_SIZE:
    - 2000.0
    - 2000.0
    - 2400.0
  VOXELS_PER_AXIS:
    - 64
    - 64
    - 64
